server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zcmjs/spring-cloud-course
          search-paths: configurationFiles #sciezka gdzie jest umieszczony katalog z folderem z plikiem
          try-master-branch: false

